@host=http://localhost:5134

POST {{host}}/auth/register HTTP/1.1
Content-Type: application/json

{
    "firstName": "User",
    "lastName": "Domian",
    "email": "user@domain.com",
    "password" : "password"
}
